services:
    GrumPHP\Locator\AsciiLocator:
        arguments:
            - '@GrumPHP\Configuration\Model\AsciiConfig'
            - '@filesystem'
            - '@GrumPHP\Util\Paths'
        public: true

    locator.external_command:
        class: GrumPHP\Locator\ExternalCommand
        factory: ['GrumPHP\Locator\ExternalCommand', 'loadWithPaths']
        arguments:
            - '@GrumPHP\Util\Paths'
            - '@executable_finder'
        public: true

    locator.changed_files:
        class: GrumPHP\Locator\ChangedFiles
        arguments:
            - '@GrumPHP\Git\GitRepository'
            - '@filesystem'
            - '@GrumPHP\Util\Paths'
        public: true

    locator.registered_files:
        class: GrumPHP\Locator\RegisteredFiles
        arguments:
            - '@GrumPHP\Git\GitRepository'
            - '@GrumPHP\Util\Paths'
        public: true

    GrumPHP\Locator\GitWorkingDirLocator:
        arguments:
            - '@executable_finder'
    GrumPHP\Locator\GitRepositoryDirLocator:
        arguments:
            - '@grumphp.util.filesystem'
    GrumPHP\Locator\GitRepositoryLocator:
        arguments:
            - '@GrumPHP\Util\Paths'
