services:
    config:
        class: GrumPHP\Configuration\GrumPHP
        arguments:
          - '@service_container'

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
          - '@service_container'

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    executable_finder:
        class: Symfony\Component\Process\ExecutableFinder

    process_builder:
      class: GrumPHP\Process\ProcessBuilder
      arguments:
        - '@config'
        - '@locator.external_command'

    git.repository:
        class: Gitonomy\Git\Repository
        arguments:
          - '%git_dir%'
          - { logger: '@grumphp.logger' }

    task_runner:
        class: GrumPHP\Runner\TaskRunner
        arguments:
          - '@config'
          - '@event_dispatcher'

    locator.external_command:
        class: GrumPHP\Locator\ExternalCommand
        arguments:
          - '%bin_dir%'
          - '@executable_finder'

    locator.configuration_file:
        class: GrumPHP\Locator\ConfigurationFile
        arguments:
          - '@filesystem'

    locator.changed_files:
        class: GrumPHP\Locator\ChangedFiles
        arguments:
          - '@git.repository'

    locator.registered_files:
        class: GrumPHP\Locator\RegisteredFiles
        arguments:
          - '@git.repository'

    grumphp.io:
        alias: grumphp.io.null

    grumphp.io.null:
        class: GrumPHP\IO\NullIO
        public: false

    grumphp.io.console:
        class: GrumPHP\IO\ConsoleIO
        synthetic: true

    grumphp.logger:
        class: Monolog\Logger
        arguments:
          - 'GrumPHP'
          - ['@grumphp.logger.handler.nullhandler']

    grumphp.logger.handler.nullhandler:
        class: Monolog\Handler\NullHandler
        public: false
