services:
    task.ant:
        class: GrumPHP\Task\Ant
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: ant}

    task.behat:
        class: GrumPHP\Task\Behat
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: behat}

    task.codeception:
        class: GrumPHP\Task\Codeception
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: codeception}

    task.composer:
        class: GrumPHP\Task\Composer
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: composer}

    task.git.gherkin:
        class: GrumPHP\Task\Gherkin
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: gherkin}

    task.git.blacklist:
        class: GrumPHP\Task\Git\Blacklist
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: git_blacklist}

    task.git.commitmessage:
        class: GrumPHP\Task\Git\CommitMessage
        arguments:
            - '@config'
        tags:
            - {name: grumphp.task, config: git_commit_message}

    task.grunt:
        class: GrumPHP\Task\Grunt
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: grunt}

    task.gulp:
        class: GrumPHP\Task\Gulp
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: gulp}
    task.jsonlint:
        class: GrumPHP\Task\JsonLint
        arguments:
            - '@config'
            - '@linter.jsonlint'
        tags:
            - {name: grumphp.task, config: jsonlint}

    task.make:
        class: GrumPHP\Task\Make
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: make}

    task.phing:
        class: GrumPHP\Task\Phing
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: phing}

    task.phpcs:
        class: GrumPHP\Task\Phpcs
        arguments:
          - '@config'
          - '@process_builder'
        tags:
          - {name: grumphp.task, config: phpcs}

    task.phpcsfixer:
        class: GrumPHP\Task\PhpCsFixer
        arguments:
          - '@config'
          - '@process_builder'
        tags:
          - {name: grumphp.task, config: phpcsfixer}

    task.phpspec:
        class: GrumPHP\Task\Phpspec
        arguments:
          - '@config'
          - '@process_builder'
        tags:
          - {name: grumphp.task, config: phpspec}

    task.phpunit:
        class: GrumPHP\Task\Phpunit
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: phpunit}

    task.robo:
        class: GrumPHP\Task\Robo
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: robo}

    task.securitychecker:
        class: GrumPHP\Task\SecurityChecker
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: securitychecker}

    task.shell:
        class: GrumPHP\Task\Shell
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: shell}

    task.xmllint:
        class: GrumPHP\Task\XmlLint
        arguments:
            - '@config'
            - '@linter.xmllint'
        tags:
            - {name: grumphp.task, config: xmllint}

    task.yamllint:
        class: GrumPHP\Task\YamlLint
        arguments:
            - '@config'
            - '@linter.yamllint'
        tags:
            - {name: grumphp.task, config: yamllint}
