language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  matrix:
    -
    - DEPENDENCIES=--prefer-lowest

cache:
  directories:
    - .composer/cache

matrix:
  fast_finish: true

before_install:
  - alias composer=composer\ --no-interaction && composer selfupdate
  - composer global require hirak/prestissimo

install:
  - travis_retry composer update --no-progress --profile --no-scripts --no-suggest $DEPENDENCIES

script:
   - bin/grumphp run

notifications:
  irc:
    skip_join: true
    channels:
      - chat.freenode.net#grumphp
